server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://db:5432/jwt_security
    username: postgres
    password: oleg
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true

    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

secretKey: 6B58703273357638792F423F4528472B4B6250655368566D597133743677397A
